2021-12-11 23:56:48,295 ERROR: Exception on /edit_profile [GET] [in /home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/adminroot/Desktop/group_assignment/app/routes.py", line 129, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile', form=form)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/adminroot/Desktop/group_assignment/app/templates/edit_profile.html", line 22, in template
    {% comment %} <p>{{form.delete()}}</p> {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-12-11 23:57:23,583 INFO: SMediApp startup [in /home/adminroot/Desktop/group_assignment/app/__init__.py:43]
2021-12-11 23:57:31,937 ERROR: Exception on /edit_profile [GET] [in /home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/adminroot/Desktop/group_assignment/app/routes.py", line 129, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile', form=form)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/adminroot/Desktop/group_assignment/app/templates/edit_profile.html", line 22, in template
    {% comment %} <p>{{form.delete()}}</p> {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-12-11 23:58:08,288 INFO: SMediApp startup [in /home/adminroot/Desktop/group_assignment/app/__init__.py:43]
2021-12-11 23:58:25,749 ERROR: Exception on /edit_profile [GET] [in /home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/adminroot/Desktop/group_assignment/app/routes.py", line 129, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile', form=form)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/adminroot/Desktop/group_assignment/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/adminroot/Desktop/group_assignment/app/templates/edit_profile.html", line 22, in template
    {% comment %} <p>{{form.delete()}}</p> {% endcomment %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-12-12 00:07:34,377 INFO: SMediApp startup [in /home/adminroot/Desktop/group_assignment/app/__init__.py:43]
2021-12-12 00:08:07,626 INFO: SMediApp startup [in /home/adminroot/Desktop/group_assignment/app/__init__.py:43]
